// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrckzdzaifzwcpqooveu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyY2t6ZHphaWZ6d2NwcW9vdmV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDkwMzgsImV4cCI6MjA2OTMyNTAzOH0.EZloJ4XSCsSHk9ylYwV0bwDGe6Akk8-E7rkpY5Q3OC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});